-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: requirements-txt-fixer
-   repo: https://github.com/pre-commit/mirrors-scss-lint
    sha: v0.48.0
    hooks:
    -   id: scss-lint
