linters:
  NameFormat:
    exclude:
      - 'assets/_revealjs.scss'
  MergeableSelector:
    enabled: false
  SelectorDepth:
    exclude:
      - 'assets/_revealjs.scss'
  ColorVariable:
    enabled: false
